version: '2'
networks:
    frontend:
    backend:
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        env_file:
            - ".env"
        networks:
            - frontend
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        #image: fpm-alpine-mysqli # uncomment this line and comment following build and image to get offical image
        build: . # install extensions via docker-php-ext-install mysqli
        image: php-fpm-mysqli
        container_name: php-fpm
        networks:
            - frontend
            - backend
        volumes:
            - ./www:/www
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    percona:
        image: percona
        container_name: percona
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - frontend
            - backend        
        volumes:
            - ./mysql:/var/lib/mysql
            - ./percona.cnf:/etc/mysql/percona-server.conf.d/percona.cnf