version: '2'
networks:
    frontend:
    backend:
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        env_file:
            - ".env"
        networks:
            - frontend
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
#        command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php-fpm:
        #image: fpm-alpine-mysqli
        build: .
        image: php-fpm-mysqli
        container_name: php-fpm
        networks:
            - frontend
            - backend
        volumes:
            - ./www:/www
    percona:
        image: percona
        container_name: percona
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - frontend
            - backend        
        volumes:
            - ./mysql:/var/lib/mysql
            - ./percona.cnf:/etc/mysql/percona-server.conf.d/percona.cnf
        networks:
            - frontend
            - backend