version: '2'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        env_file:
            - ".env"
        environment:
           - NGINX_HOST=${NGINX_HOST}
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./hostname.conf:/etc/nginx/conf.d/web.template
        command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        links:
          - php-fpm
    php-fpm:
        #image: fpm-alpine-mysqli
        build: .
        image: php-fpm-mysqli
        container_name: php-fpm
        volumes:
                - ./www:/www
        links:
          - percona
    percona:
        image: percona
        container_name: percona
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./percona.cnf:/etc/mysql/percona-server.conf.d/percona.cnf